/**
 *
 * $Id$
 */
package eMProject.validation;

import eMProject.Animal;
import eMProject.Soigneur;
import eMProject.Zoo;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eMProject.Enclos}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnclosValidator {
	boolean validate();

	boolean validateAnimal(EList<Animal> value);

	boolean validateZoo(Zoo value);

	boolean validateSoigneur(EList<Soigneur> value);

	boolean validateId(int value);

	boolean validateId(EList<Integer> value);
}
