/**
 *
 * $Id$
 */
package eMProject.validation;

import eMProject.Enclos;
import eMProject.Soigneur;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eMProject.Zoo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ZooValidator {
	boolean validate();

	boolean validateEnclos(EList<Enclos> value);

	boolean validateSoigneur(EList<Soigneur> value);

	boolean validateId(int value);

	boolean validateId(EList<Integer> value);
}
